@startuml eCaseDiagram
left to right direction

' Atores
actor Cliente
actor Administrador

' Casos de o do Cliente
Cliente --> (Registar conta)
Cliente --> (Login)
Cliente --> (Logout)
Cliente --> (Recuperar password)
Cliente --> (Consultar moedas)
Cliente --> (Ver detalhes de moeda)

Cliente --> (Ver saldo e carteira)
Cliente --> (Depositar fundos)
Cliente --> (Comprar criptomoeda)
Cliente --> (Vender criptomoeda)
Cliente --> (Consultar histórico de transações)


' Casos de o do Administrador
Administrador --> (Gerir utilizadores)
Administrador --> (Gerir criptomoedas)



' Relações internas
(Comprar criptomoeda) --> (Validar fundos) : includes
(Comprar criptomoeda) --> (Matching de ordens) : includes
(Vender criptomoeda) --> (Matching de ordens) : includes
(Consultar moedas) <-- (Filtrar moedas) : extends
(Consultar moedas) <-- (Ver detalhes de moeda) : extends
(Comprar criptomoeda) --> (Atualizar valor da moeda) : includes
(Consultar moedas) --> (Atualizar valor da moeda) : includes

@enduml
